backbone: resnet18
batch_size: 128
colorized_scar: true
duplication: true
imsize: !!python/tuple
- 256
- 256
latent_space_dims:
- 512
- 512
lr: 0.03
min_dataset_length: 500
num_classes: 3
num_epochs: 50
patch_localization: false
patch_size: 64
polygoned: true
root_dir: dataset/metal_nut/
seed: 123456789
subject: metal_nut
train_val_split: 0.2
