batch_size: 96
duplication: true
imsize: !!python/tuple
- 256
- 256
min_dataset_length: 500
patch_localization: false
patch_size: 64
root_dir: dataset/grid/
seed: 123456789
subject: grid
train_val_split: 0.2
